[project]
name = "advance-dfn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "addict>=2.4.0",
    "datasets>=5.0.0",
    "dpdfnet>=0.5.1",
    "ffmpeg>=1.4",
    "modelscope>=1.37.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "psutil>=7.2.2",
    "pyloudnorm>=0.2.0",
    "soundfile>=0.14.0",
    "torch>=2.12.1",
    "torchaudio>=2.11.0",
]
